{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: network-policy-dmm-allow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-oss-dmm-kf-op-sz-kafka-bootstrap
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: eric-oss-pm-stats-exporter
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: eric-oss-pm-stats-calculator
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: eric-oss-pm-stats-query-service
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: eric-oss-pm-stats-exporter-release
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: eric-oss-pm-stats-query-service-release
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: eric-oss-pm-stats-calc-handling-test   
      ports:
        - port: 9092
        - port: 9093
{{- end }}