{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: network-policy-data-loader-data-catalog-allow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-oss-data-catalog
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: eric-oss-data-loader
      ports:
        - port: 9590
{{- end }}
