kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: network-policy-data-loader-dmm-allow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-oss-dmm-kf-op-sz-kafka-bootstrap
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: eric-oss-data-loader
      ports:
        - port: 9092
        - port: 9093