{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: network-policy-calculator-allow
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-oss-pm-stats-calculator
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: eric-oss-pm-stats-exporter
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: eric-oss-pm-stats-calc-handling-test
      ports:
        - port: 8080
{{- end }}
