apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-oss-pm-stats-calc-handling-test.fullname" . }}-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
