apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-oss-pm-stats-calc-handling-test.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ template "eric-oss-pm-stats-calc-handling-test.fullname" . }}-service-account
roleRef:
  kind: Role
  name: {{ template "eric-oss-pm-stats-calc-handling-test.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
