apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "eric-oss-pm-stats-calc-handling-test.labels" . | nindent 4 }}
    {{- include "eric-oss-pm-stats-calc-handling-test.service-mesh-inject" . | nindent 4 }}
    {{- include "eric-oss-pm-stats-calc-handling-test.service-mesh-ism2osm-labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-pm-stats-calc-handling-test.service-mesh-inject" . | nindent 4 }}
    {{- include "eric-oss-pm-stats-calc-handling-test.service-mesh-version" . | nindent 4 }}
    {{- include "eric-oss-pm-stats-calc-handling-test.service-mesh-volume" . | nindent 4 }}
spec:
  containers:
    - name: "{{ $.Chart.Name }}"
      image: {{ $.Values.images.testwareImage | quote }}
      env:
        - name: TESTWARE_NAME
          value: {{ $.Values.env.TESTWARE_NAME }}
        - name: STAGING_TYPE
          value: {{ $.Values.env.STAGING_TYPE }}
        - name: ENVIRONMENT
          value: {{ $.Values.env.ENVIRONMENT }}
        - name: BUILD_URL
          value: {{ $.Values.env.BUILD_URL }}
        - name: APP_NAME
          value: {{ $.Values.env.APP_NAME }}
        - name: APP_VERSION
          value: "{{ include "get-application-version" $ | trim | default "undefined" }}"
        - name: PRODUCT
          value: {{ $.Values.env.PRODUCT }}
        - name: PRODUCT_VERSION
          value: "{{ include "get-product-version" $ | trim | default "undefined" }}"
        - name: TARGET_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: testware-global-config
              key: cluster-name
        - name: TARGET_NAMESPACE
          value: {{ $.Release.Namespace }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: database_url
        - name: K6_TOOL_GUI_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: gui_url
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: api_url
        - name: MAIN_TEST_FILE
          value: {{ $.Values.env.MAIN_TEST_FILE }}
        - name: OPTIONS_FILE
          value: {{ $.Values.env.OPTIONS_FILE }}
        - name: HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: testware-hostnames
              key: gas
        - name: EIC_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: testware-hostnames
              key: eic
        - name: SEF_STATUS
          value: {{ $.Values.env.SEF_STATUS | quote }}
        - name: SEF_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: eric-cncs-oss-config-iam-client-secret
              key: clientSecret
        - name: SEF_ADMIN_USER
          value: {{ $.Values.env.SEF_ADMIN_USER }}
        - name: SEF_ADMIN_PASSWORD
          value: {{ $.Values.env.SEF_ADMIN_PASSWORD }}
        - name: APIGW_USER
          value: {{ $.Values.env.APIGW_USER }}
        - name: APIGW_PASSWORD
          value: {{ $.Values.env.APIGW_PASSWORD }}
        - name: DATA_CATALOG_HOSTNAME
          value: {{ $.Values.env.DATA_CATALOG_HOSTNAME }}
        - name: SCHEMA_REGISTRY_HOSTNAME
          value: {{ $.Values.env.SCHEMA_REGISTRY_HOSTNAME }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ include "eric-oss-pm-stats-calc-handling-test.kafka-bootstrap-server" . }}
        - name: KPI_SET
          value: {{ $.Values.env.KPI_SET }}
        - name: THRESHOLDS
          value: {{ $.Values.env.THRESHOLDS | quote }}
      imagePullPolicy: Always
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        runAsNonRoot: false
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
    - name: "{{ $.Chart.Name }}-kafka-sidecar"
      image: {{ $.Values.images.kafkaSidecarImage | quote }}
      imagePullPolicy: Always
      ports:
        - name: kafka-sidecar
          containerPort: 8082
      env:
        - name: SCHEMA_REGISTRY_HOSTNAME
          value: {{ $.Values.env.SCHEMA_REGISTRY_HOSTNAME }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ include "eric-oss-pm-stats-calc-handling-test.kafka-bootstrap-server" . }}
  serviceAccountName: {{ template "eric-oss-pm-stats-calc-handling-test.fullname" . }}-service-account
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: k8s-registry-secret
  schedulerName: default-scheduler
  restartPolicy: Never
  securityContext: {}
  terminationGracePeriodSeconds: 5
